/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getRoot_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getHealth_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/trades': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all trades */
    get: operations['TradesController_findMany_v1'];
    put?: never;
    /** Create a new trade */
    post: operations['TradesController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/trades/{uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a trade by UUID */
    get: operations['TradesController_findByUuid_v1'];
    /** Update a trade by UUID */
    put: operations['TradesController_updateByUuid_v1'];
    post?: never;
    /** Delete a trade by UUID */
    delete: operations['TradesController_deleteByUuid_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/trade-groups': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all trade groups with metrics */
    get: operations['TradeGroupsController_findMany_v1'];
    put?: never;
    /** Create a new trade group */
    post: operations['TradeGroupsController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/trade-groups/{uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a trade group by UUID */
    get: operations['TradeGroupsController_findByUuid_v1'];
    put?: never;
    post?: never;
    /** Delete a trade group by UUID */
    delete: operations['TradeGroupsController_deleteByUuid_v1'];
    options?: never;
    head?: never;
    /** Partially update a trade group by UUID */
    patch: operations['TradeGroupsController_updateByUuid_v1'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateTradeDto: {
      /**
       * @description Stock symbol
       * @example AAPL
       */
      symbol: string;
      /**
       * @description Strike price of the option
       * @example 150
       */
      strikePrice: number;
      /**
       * Format: date-time
       * @description Expiry date (ISO 8601 DateTime format)
       * @example 2026-02-15T00:00:00.000Z
       */
      expiryDate: string;
      /**
       * @description Trade type (BUY or SELL)
       * @example BUY
       * @enum {string}
       */
      tradeType: 'BUY' | 'SELL';
      /**
       * @description Option type (CALL or PUT)
       * @example CALL
       * @enum {string}
       */
      optionType: 'CALL' | 'PUT';
      /**
       * @description Number of contracts
       * @example 10
       */
      quantity: number;
      /**
       * @description Total cost basis
       * @example 1500
       */
      costBasis: number;
      /**
       * @description Current value of the position
       * @example 1750
       */
      currentValue: number;
      /**
       * @description Optional notes
       * @example Long call position on AAPL
       */
      notes?: string;
      /**
       * @description Optional trade group UUID
       * @example a3bb189e-8bf9-3888-9912-ace4e6543002
       */
      tradeGroupUuid?: string;
    };
    UpdateTradeDto: {
      /**
       * @description Trade status
       * @example CLOSING_SOON
       * @enum {string}
       */
      status?: 'OPEN' | 'CLOSING_SOON' | 'CLOSED';
    };
    CreateTradeGroupDto: {
      /**
       * @description Trade group name
       * @example Calendar Spread Feb-15-2026
       */
      name: string;
      /**
       * @description Strategy type for the trade group
       * @example CALENDAR_SPREAD
       * @enum {string}
       */
      strategyType: 'CALENDAR_SPREAD' | 'RATIO_CALENDAR_SPREAD' | 'CUSTOM';
      /**
       * @description Array of trade UUIDs to include in the trade group (minimum 2 required)
       * @example [
       *       "a3bb189e-8bf9-3888-9912-ace4e6543001",
       *       "a3bb189e-8bf9-3888-9912-ace4e6543002"
       *     ]
       */
      tradeUuids: string[];
      /**
       * @description Optional notes about the trade group
       * @example Selling Feb-15 $150 call, buying Mar-15 $150 call
       */
      notes?: string;
    };
    UpdateTradeGroupDto: {
      /**
       * @description Trade group name
       * @example Calendar Spread Feb-15-2026 (UPDATED)
       */
      name?: string;
      /**
       * @description Strategy type for the trade group
       * @example CUSTOM
       * @enum {string}
       */
      strategyType?: 'CALENDAR_SPREAD' | 'RATIO_CALENDAR_SPREAD' | 'CUSTOM';
      /**
       * @description Optional notes about the trade group
       * @example Updated notes for this trade group
       */
      notes?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getRoot_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppController_getHealth_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TradesController_findMany_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all trades */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TradesController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTradeDto'];
      };
    };
    responses: {
      /** @description Trade created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TradesController_findByUuid_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Trade UUID */
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trade found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TradesController_updateByUuid_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Trade UUID */
        uuid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTradeDto'];
      };
    };
    responses: {
      /** @description Trade updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TradesController_deleteByUuid_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Trade UUID */
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trade deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TradeGroupsController_findMany_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all trade groups */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TradeGroupsController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTradeGroupDto'];
      };
    };
    responses: {
      /** @description Trade group created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TradeGroupsController_findByUuid_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Trade group UUID */
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trade group found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TradeGroupsController_deleteByUuid_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Trade group UUID */
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trade group deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TradeGroupsController_updateByUuid_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Trade group UUID */
        uuid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTradeGroupDto'];
      };
    };
    responses: {
      /** @description Trade group updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
