// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import { defineConfig } from 'prisma/config';
import path from 'path';

// Load the appropriate env file based on NODE_ENV
const envFile = process.env.NODE_ENV ? `config/${process.env.NODE_ENV}.env` : 'config/development.env';

dotenv.config({ path: path.join(process.cwd(), envFile) });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
